// This file has been autogenerated from a class added in the UI designer.

using System;

using UIKit;

namespace MyTrips.iOS
{
	public partial class SettingDetailTableViewCell : UITableViewCell
	{
		public SettingDetailTableViewCell (IntPtr handle) : base (handle) { }

		public string Name
		{
			get { return settingNameLabel.Text; }
			set { settingNameLabel.Text = value; }
		}

		public bool Checked
		{
			get { return Accessory == UITableViewCellAccessory.Checkmark ? true : false; }
			set 
			{ 
				if (value == true)
					Accessory = UITableViewCellAccessory.Checkmark;
				else
					Accessory = UITableViewCellAccessory.None; 
			}
		}
	}
}
