// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyTrips.iOS
{
	public partial class SettingDetailTextTableViewCell : UITextField
	{
		public SettingDetailTextTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
